### ISSUE TITLE
Crate name

### ISSUE THREAD

**Issue by dralley** [rpm-rs/rpmspec-rs#1]
There is already an "rpmspec" crate, but it is abandoned.  Seems like the versions got yanked and the repository was deleted.

https://crates.io/crates/rpmspec

I'm reaching out to ask about whether they'd be willing to transfer ownership.

**Comment by windowsboy111** [comment]
https://crates.io/users/vv9k
What about mentioning him here directly? Maybe it'd be easier to communicate.

**Comment by dralley** [comment]
No need, I have it already, adding you
