### ISSUE TITLE
Spec file builder

### ISSUE THREAD

**Issue by madonuko** [rpm-rs/rpmspec-rs#2]
It might be useful to add a `SpecBuilder` (opposite of `SpecParser`?). This allows generating a spec file using pure Rust.

**Comment by dralley** [comment]
Ideally we can merge with the "specfile" create which is exactly that.

**Comment by windowsboy111** [comment]
That's exactly where I got the idea from, but I can't find the repository from the original author's GitHub page.

**Comment by dralley** [comment]
Yes, I'm not sure why they purged it all.  At minimum there's a copy inside the crates that can be downloaded, but it'd still be nice to ask first.
